[Tue Jul  8 14:23:01 EEST 2025] Запуск Zadarma бота...
/usr/bin/python3
bot.py:47: TelegramDeprecationWarning: Old Handler API is deprecated - see https://git.io/fxJuV for details
  updater = Updater(TELEGRAM_TOKEN)
2025-07-08 14:23:01,895 - telegram.ext.updater - ERROR - unhandled exception in Bot:8030228734:dispatcher
Traceback (most recent call last):
  File "/home/gomoncli/.local/lib/python3.6/site-packages/telegram/ext/updater.py", line 215, in _thread_wrapper
    target(*args, **kwargs)
  File "/home/gomoncli/.local/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 260, in start
    self._init_async_threads(uuid4(), self.workers)
  File "/home/gomoncli/.local/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 176, in _init_async_threads
    thread.start()
  File "/usr/lib64/python3.6/threading.py", line 867, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
Exception in thread Bot:8030228734:dispatcher:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 937, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.6/threading.py", line 885, in run
    self._target(*self._args, **self._kwargs)
  File "/home/gomoncli/.local/lib/python3.6/site-packages/telegram/ext/updater.py", line 215, in _thread_wrapper
    target(*args, **kwargs)
  File "/home/gomoncli/.local/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 260, in start
    self._init_async_threads(uuid4(), self.workers)
  File "/home/gomoncli/.local/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 176, in _init_async_threads
    thread.start()
  File "/usr/lib64/python3.6/threading.py", line 867, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread

2025-07-08 14:23:05,984 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-07-08 14:23:11,544 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-07-08 14:23:18,358 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-07-08 14:23:24,051 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-07-08 14:23:32,554 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-07-08 14:23:45,280 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-07-08 14:24:04,340 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-07-08 14:24:25,509 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-07-08 14:24:55,227 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-07-08 14:25:37,734 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
bot.py:47: TelegramDeprecationWarning: Old Handler API is deprecated - see https://git.io/fxJuV for details
  updater = Updater(TELEGRAM_TOKEN)
2025-07-08 14:37:35,109 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-07-08 14:37:35,155 - telegram.ext.dispatcher - ERROR - An uncaught error was raised while handling the error
Traceback (most recent call last):
  File "/home/gomoncli/.local/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 326, in process_update
    self.dispatch_error(None, update)
  File "/home/gomoncli/.local/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 524, in dispatch_error
    callback(self.bot, update, error)
TypeError: error() takes 2 positional arguments but 3 were given
2025-07-08 14:37:40,190 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-07-08 14:37:40,220 - telegram.ext.dispatcher - ERROR - An uncaught error was raised while handling the error
Traceback (most recent call last):
  File "/home/gomoncli/.local/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 326, in process_update
    self.dispatch_error(None, update)
  File "/home/gomoncli/.local/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 524, in dispatch_error
    callback(self.bot, update, error)
TypeError: error() takes 2 positional arguments but 3 were given
2025-07-08 14:37:46,249 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-07-08 14:37:46,253 - telegram.ext.dispatcher - ERROR - An uncaught error was raised while handling the error
Traceback (most recent call last):
  File "/home/gomoncli/.local/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 326, in process_update
    self.dispatch_error(None, update)
  File "/home/gomoncli/.local/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 524, in dispatch_error
    callback(self.bot, update, error)
TypeError: error() takes 2 positional arguments but 3 were given
2025-07-08 14:37:53,810 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-07-08 14:37:53,820 - telegram.ext.dispatcher - ERROR - An uncaught error was raised while handling the error
Traceback (most recent call last):
  File "/home/gomoncli/.local/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 326, in process_update
    self.dispatch_error(None, update)
  File "/home/gomoncli/.local/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 524, in dispatch_error
    callback(self.bot, update, error)
TypeError: error() takes 2 positional arguments but 3 were given
2025-07-08 14:38:00,624 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-07-08 14:38:00,636 - telegram.ext.dispatcher - ERROR - An uncaught error was raised while handling the error
Traceback (most recent call last):
  File "/home/gomoncli/.local/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 326, in process_update
    self.dispatch_error(None, update)
  File "/home/gomoncli/.local/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 524, in dispatch_error
    callback(self.bot, update, error)
TypeError: error() takes 2 positional arguments but 3 were given
2025-07-08 14:38:10,815 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-07-08 14:38:10,853 - telegram.ext.dispatcher - ERROR - An uncaught error was raised while handling the error
Traceback (most recent call last):
  File "/home/gomoncli/.local/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 326, in process_update
    self.dispatch_error(None, update)
  File "/home/gomoncli/.local/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 524, in dispatch_error
    callback(self.bot, update, error)
TypeError: error() takes 2 positional arguments but 3 were given
2025-07-08 14:38:26,077 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-07-08 14:38:26,120 - telegram.ext.dispatcher - ERROR - An uncaught error was raised while handling the error
Traceback (most recent call last):
  File "/home/gomoncli/.local/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 326, in process_update
    self.dispatch_error(None, update)
  File "/home/gomoncli/.local/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 524, in dispatch_error
    callback(self.bot, update, error)
TypeError: error() takes 2 positional arguments but 3 were given
2025-07-08 14:38:41,538 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-07-08 14:38:41,589 - telegram.ext.dispatcher - ERROR - An uncaught error was raised while handling the error
Traceback (most recent call last):
  File "/home/gomoncli/.local/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 326, in process_update
    self.dispatch_error(None, update)
  File "/home/gomoncli/.local/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 524, in dispatch_error
    callback(self.bot, update, error)
TypeError: error() takes 2 positional arguments but 3 were given
2025-07-08 14:39:02,698 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-07-08 14:39:02,707 - telegram.ext.dispatcher - ERROR - An uncaught error was raised while handling the error
Traceback (most recent call last):
  File "/home/gomoncli/.local/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 326, in process_update
    self.dispatch_error(None, update)
  File "/home/gomoncli/.local/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 524, in dispatch_error
    callback(self.bot, update, error)
TypeError: error() takes 2 positional arguments but 3 were given
2025-07-08 14:39:32,411 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-07-08 14:39:32,427 - telegram.ext.dispatcher - ERROR - An uncaught error was raised while handling the error
Traceback (most recent call last):
  File "/home/gomoncli/.local/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 326, in process_update
    self.dispatch_error(None, update)
  File "/home/gomoncli/.local/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 524, in dispatch_error
    callback(self.bot, update, error)
TypeError: error() takes 2 positional arguments but 3 were given
2025-07-08 14:40:14,951 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-07-08 14:40:15,000 - telegram.ext.dispatcher - ERROR - An uncaught error was raised while handling the error
Traceback (most recent call last):
  File "/home/gomoncli/.local/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 326, in process_update
    self.dispatch_error(None, update)
  File "/home/gomoncli/.local/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 524, in dispatch_error
    callback(self.bot, update, error)
TypeError: error() takes 2 positional arguments but 3 were given
